import React, {useRef} from 'react'
import { Canvas, useFrame } from "@react-three/fiber";
import {OrbitControls, useGLTF} from "@react-three/drei";

const Room = () => {
  return (
    <div style={{
      border: '2px solid red',
      position: 'absolute',
      top: "0",
      left: "0",
      height: "100%",
      width: "100%",
    }}>
      <Canvas>
      <OrbitControls />
      <ambientLight intensity={0.5} />
      <Model />
    </Canvas>

    </div>
    
  )
}

export default Room


/* Model design to be used */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

export function Model(props) {
  const { nodes, materials } = useGLTF("/world_home.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FLoor.geometry}
        material={materials["Material.007"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PLanks.geometry}
        material={materials["Material.008"]}
        position={[-0.85, 0.06, 0]}
        scale={[0.11, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_1.geometry}
        material={materials["Material.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Material.017"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_1.geometry}
        material={materials["Material.018"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shelf.geometry}
        material={materials["Material.019"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.010"]}
        position={[0.35, 0.2, -0.05]}
        rotation={[-Math.PI, 1.57, -Math.PI]}
        scale={[0.66, 0.47, 0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backboard_1.geometry}
        material={materials["Material.009"]}
        position={[0.36, 0.24, 0.53]}
        rotation={[0, -1.57, -Math.PI]}
        scale={[-0.04, -0.15, -0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.backboard_2.geometry}
        material={materials["Material.012"]}
        position={[0.36, 0.24, 0.53]}
        rotation={[0, -1.57, -Math.PI]}
        scale={[-0.04, -0.15, -0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.frontboard_1.geometry}
        material={materials["Material.011"]}
        position={[0.36, 0.24, -0.69]}
        rotation={[0, -1.57, -Math.PI]}
        scale={[-0.04, -0.15, -0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.front_board_2.geometry}
        material={materials["Material.013"]}
        position={[0.36, 0.24, -0.69]}
        rotation={[0, -1.57, -Math.PI]}
        scale={[-0.04, -0.15, -0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.016"]}
        position={[0.27, -0.18, 0.67]}
        scale={[0.1, 0.12, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[0.33, 0.21, -0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials["Material.015"]}
        position={[0.28, 0.08, 0.25]}
        scale={[1, 1, 0.48]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[0.34, 0.27, -0.5]}
        scale={[0.43, 0.79, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials["Material.014"]}
        position={[0.34, 0.27, -0.5]}
        scale={[0.43, 0.79, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["Material.025"]}
        position={[-0.62, 0.06, -0.53]}
        scale={0.23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials["Material.024"]}
        position={[-0.62, 0.06, -0.53]}
        scale={0.23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Material.026"]}
        position={[-0.62, 0.06, -0.53]}
        scale={0.23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials["Material.027"]}
        position={[-0.62, 0.35, -0.32]}
        scale={0.02}
      />
      <group position={[-0.62, 0.55, -0.5]} scale={0.11}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_1.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_2.geometry}
          material={materials["Material.029"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={materials["Material.020"]}
        position={[0.08, 1.07, -0.71]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.06, -0.1, -0.08]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.021"]}
          position={[0.02, -0.98, -0.04]}
          rotation={[0, 0, -Math.PI]}
          scale={[0.66, 0.43, 0.54]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Material.022"]}
        position={[-0.21, 0.93, -0.79]}
        scale={[0.09, 0.11, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials["Material.023"]}
        position={[-0.21, 0.97, -0.79]}
        rotation={[0, -0.7, 0]}
        scale={[0.09, 0.17, 0.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["Material.006"]}
        position={[-0.46, 0.06, 0.2]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.23, -0.23, -0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={nodes.Plane012.material}
        position={[-0.46, -0.7, 0.2]}
        scale={-19.65}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials["Material.005"]}
        position={[-0.88, -0.54, 1.6]}
        scale={-19.65}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={materials["Material.030"]}
        position={[-0.64, 1.04, -0.74]}
        scale={0.12}
      />
    </group>
  );
}

useGLTF.preload("/world_home.glb");
